In [11]:
import pandas as pd

df = pd.read_csv('../data/GAST-GT-08-31-24-PLAYS')
# df['converted'] = df['yds'] >= df['ytg']
# df.to_csv('../data/GAST-GT-08-31-24-PLAYS',index=False)
print(len(df))
df

61

    down  ytg  field_pos     player action completed  yds  converted
0      1   10          1     haynes   rush       NaN    1      False
1      2    9          2  singleton    rec     False    0      False
2      3    9          2  singleton    rec      True   12       True
3      1   10         14       lane    rec      True   12       True
4      1   10         26     haynes   rush       NaN    3      False
..   ...  ...        ...        ...    ...       ...  ...        ...
56     1   10         53      pyron   rush       NaN    4      False
57     2    6         57     carrie   rush       NaN    3      False
58     3    3         60      pyron   rush       NaN   11       True
59     1   10         71     carrie    rec      True   -1      False
60     2   11         70     carrie   rush       NaN    4      False

[61 rows x 8 columns]

In [12]:


# Determine Pass / Rush Ratio
plays = len(df)
passing_df = df[df['action']=='rec']
rushing_df = df[df['action']=='rush']
# plays == len(passing_df)+len(rushing_df)
p_ratio = (len(passing_df)/plays)*100
r_ratio = (len(rushing_df)/plays)*100

# Avg Yds per Rec
p_avg = passing_df['yds'].mean()
# Avg Yds per Carry
r_avg = rushing_df['yds'].mean()

# Completion %
comp_df = passing_df[passing_df['completed']==True]
comp_pct = len(comp_df)/len(passing_df)

# Effective Carry %
eff_car_df = rushing_df[(rushing_df['yds']>5.0) | (rushing_df['converted']==True)]
eff_car_pct = len(eff_car_df)/len(rushing_df)

print('Plays : ' + str(plays))
print('Passing (' + str(round(p_ratio,2)) + '%) @ ' + str(round(comp_pct,2)) + 
      ' cmp for ' + str(round(p_avg,1)) + ' yd avg')
print('Rushing (' + str(round(r_ratio,2)) + '%) @ ' + str(round(eff_car_pct,2)) + 
      ' eff for ' + str(round(r_avg,1)) + ' yd avg')

Plays : 61
Passing (47.54%) @ 0.86 cmp for 9.4 yd avg
Rushing (52.46%) @ 0.41 eff for 6.9 yd avg

In [13]:
skill_players_rec = passing_df['player'].unique().tolist()
skill_players_rush = rushing_df['player'].unique().tolist()

In [14]:
results = {}

for player in skill_players_rec:
    if player not in results.keys():
        results[player] = {}
    df_player = df[df['player']==player]   
    df_player_rec = df_player[df_player['action']=='rec']
    # Plays     
    results[player]['plays'] = len(df_player_rec)
    # Cmp 
    results[player]['targets'] = len(df_player_rec)
    df_player_cmp = df_player_rec[df_player_rec['completed']==True]
    results[player]['cmp'] = len(df_player_cmp)
    # Yds
    rec_yds = df_player_cmp['yds'].sum()
    results[player]['rec_yds'] = rec_yds
    
results

{'singleton': {'plays': 5, 'targets': 5, 'cmp': 4, 'rec_yds': 43},
 'lane': {'plays': 3, 'targets': 3, 'cmp': 3, 'rec_yds': 37},
 'boyd': {'plays': 5, 'targets': 5, 'cmp': 4, 'rec_yds': 27},
 'rutherford': {'plays': 9, 'targets': 9, 'cmp': 7, 'rec_yds': 131},
 'hawes': {'plays': 1, 'targets': 1, 'cmp': 1, 'rec_yds': 10},
 'haynes': {'plays': 1, 'targets': 1, 'cmp': 1, 'rec_yds': -6},
 'stockton': {'plays': 1, 'targets': 1, 'cmp': 1, 'rec_yds': 9},
 'leary': {'plays': 1, 'targets': 1, 'cmp': 1, 'rec_yds': 2},
 'goede': {'plays': 1, 'targets': 1, 'cmp': 1, 'rec_yds': 16},
 'beetham': {'plays': 1, 'targets': 1, 'cmp': 1, 'rec_yds': 6},
 'carrie': {'plays': 1, 'targets': 1, 'cmp': 1, 'rec_yds': -1}}

In [15]:
for player in skill_players_rush:
    if player not in results.keys():
        results[player] = {}
    df_player = df[df['player']==player]   
    df_player_rush = df_player[df_player['action']=='rush']
    # Plays    
    if 'plays' not in results[player].keys(): 
        results[player]['plays'] = len(df_player_rush)
    else:
        results[player]['plays'] += len(df_player_rush)
    # Effective Carries
    results[player]['car'] = len(df_player_rush)
    df_player_eff = df_player_rush[(df_player_rush['yds']>5.0) | (df_player_rush['converted']==True)]
    results[player]['eff_car'] = len(df_player_eff)
    # Yds
    rush_yds = df_player_rush['yds'].sum()
    results[player]['rush_yds'] = rush_yds

results

{'singleton': {'plays': 6,
  'targets': 5,
  'cmp': 4,
  'rec_yds': 43,
  'car': 1,
  'eff_car': 1,
  'rush_yds': 35},
 'lane': {'plays': 3, 'targets': 3, 'cmp': 3, 'rec_yds': 37},
 'boyd': {'plays': 5, 'targets': 5, 'cmp': 4, 'rec_yds': 27},
 'rutherford': {'plays': 9, 'targets': 9, 'cmp': 7, 'rec_yds': 131},
 'hawes': {'plays': 1, 'targets': 1, 'cmp': 1, 'rec_yds': 10},
 'haynes': {'plays': 17,
  'targets': 1,
  'cmp': 1,
  'rec_yds': -6,
  'car': 16,
  'eff_car': 5,
  'rush_yds': 82},
 'stockton': {'plays': 1, 'targets': 1, 'cmp': 1, 'rec_yds': 9},
 'leary': {'plays': 1, 'targets': 1, 'cmp': 1, 'rec_yds': 2},
 'goede': {'plays': 1, 'targets': 1, 'cmp': 1, 'rec_yds': 16},
 'beetham': {'plays': 1, 'targets': 1, 'cmp': 1, 'rec_yds': 6},
 'carrie': {'plays': 5,
  'targets': 1,
  'cmp': 1,
  'rec_yds': -1,
  'car': 4,
  'eff_car': 1,
  'rush_yds': 41},
 'king': {'plays': 5, 'car': 5, 'eff_car': 2, 'rush_yds': 27},
 'alexander': {'plays': 4, 'car': 4, 'eff_car': 3, 'rush_yds': 20},
 'pyron': {'plays': 2, 'car': 2, 'eff_car': 1, 'rush_yds': 15}}